<a href="https://colab.research.google.com/github/Safiyabegum52/Simple-registration-form-/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")

hi

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/ttd task/titanic.txt")

In [ ]:
import os

directory_path = "/content/drive/MyDrive/ttd task/"
print(f"Contents of '{directory_path}':")
for item in os.listdir(directory_path):
    print(item)

Contents of '/content/drive/MyDrive/ttd task/':
Ttdtask
titanic.txt
Untitled0.ipynb

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/intern/economic-survey-of-manufacturing-december-2025-quarter.csv")

In [ ]:
df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,MFGQ.SFA1CA,1992.12,2493.370,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
1,MFGQ.SFA1CA,1993.03,3209.200,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
2,MFGQ.SFA1CA,1993.06,2780.170,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
3,MFGQ.SFA1CA,1993.09,1933.010,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
4,MFGQ.SFA1CA,1993.12,2692.920,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30766,MFGQ.SFZ5KA,2024.12,10643.807,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30767,MFGQ.SFZ5KA,2025.03,10863.217,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30768,MFGQ.SFZ5KA,2025.06,9086.747,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30769,MFGQ.SFZ5KA,2025.09,9448.195,NaN,R,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30770,MFGQ.SFZ5KA,2025.12,10449.981,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN

In [ ]:
df.head()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,MFGQ.SFA1CA,1992.12,2493.37,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
1,MFGQ.SFA1CA,1993.03,3209.20,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
2,MFGQ.SFA1CA,1993.06,2780.17,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
3,MFGQ.SFA1CA,1993.09,1933.01,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
4,MFGQ.SFA1CA,1993.12,2692.92,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN

In [ ]:
df.tail()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
30766,MFGQ.SFZ5KA,2024.12,10643.807,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30767,MFGQ.SFZ5KA,2025.03,10863.217,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30768,MFGQ.SFZ5KA,2025.06,9086.747,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30769,MFGQ.SFZ5KA,2025.09,9448.195,NaN,R,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN
30770,MFGQ.SFZ5KA,2025.12,10449.981,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,All manufacturing,"Stocks of finished goods, trading goods and wo...","Deflated, at September 2010 quarter prices",Unadjusted,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30771 entries, 0 to 30770
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  30771 non-null  object
 1   Period            30771 non-null  float64
 2   Data_value        30022 non-null  float64
 3   Suppressed        2 non-null      object
 4   STATUS            30771 non-null  object
 5   UNITS             30771 non-null  object
 6   Magnitude         30771 non-null  int64
 7   Subject           30771 non-null  object
 8   Group             30771 non-null  object
 9   Series_title_1    30771 non-null  object
 10  Series_title_2    30771 non-null  object
 11  Series_title_3    30771 non-null  object
 12  Series_title_4    30771 non-null  object
 13  Series_title_5    1494 non-null   object
dtypes: float64(2), int64(1), object(11)
memory usage: 3.3+ MB

In [ ]:
df.describe()

             Period    Data_value     Magnitude
count  30771.000000  30022.000000  30771.000000
mean    2009.332826   2997.387560      5.708687
std        9.387814   5307.566663      1.289601
min     1992.120000    -26.000000      0.000000
25%     2001.090000    380.111000      6.000000
50%     2009.120000    981.310000      6.000000
75%     2017.120000   2224.295750      6.000000
max     2025.120000  36815.633000      6.000000

In [ ]:
df.shape

(30771, 14)

In [ ]:
df.columns

Index(['Series_reference', 'Period', 'Data_value', 'Suppressed', 'STATUS',
       'UNITS', 'Magnitude', 'Subject', 'Group', 'Series_title_1',
       'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')

In [ ]:
df.dtypes

Series_reference     object
Period              float64
Data_value          float64
Suppressed           object
STATUS               object
UNITS                object
Magnitude             int64
Subject              object
Group                object
Series_title_1       object
Series_title_2       object
Series_title_3       object
Series_title_4       object
Series_title_5       object
dtype: object

In [ ]:
df.value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df.groupby('Subject')

In [ ]:
# To fix this error, you need to provide another DataFrame to merge with.
# For example, if you have a DataFrame named 'df2':
# df.merge(df2)
# df.merge(df2, on='common_column')

# As no other DataFrame is defined, this line will still produce an error.
# You can create a dummy DataFrame to see how it works:
# df2 = pd.DataFrame({'common_column': [1, 2, 3], 'new_data': ['A', 'B', 'C']})
# df.merge(df2, left_on='Series_reference', right_on='common_column') # Example using an existing column from df

TypeError: DataFrame.merge() missing 1 required positional argument: 'right'

In [ ]:
df.sort_values()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [ ]:
df = df.drop('Period', axis=1)
display(df.head())

,Series_reference,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,MFGQ.SFA1CA,2493.37,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
1,MFGQ.SFA1CA,3209.20,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
2,MFGQ.SFA1CA,2780.17,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
3,MFGQ.SFA1CA,1933.01,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN
4,MFGQ.SFA1CA,2692.92,NaN,F,Dollars,6,Manufacturing Survey (ANZSIC06) - MFG,Industry by variable - Subannual Financial Col...,Meat and dairy product manufacturing,Sales (operating income),Current prices,Unadjusted,NaN

In [ ]:
print(df.groupby)

<bound method DataFrame.groupby of       Series_reference  Data_value Suppressed STATUS    UNITS  Magnitude  \
0          MFGQ.SFA1CA    2493.370        NaN      F  Dollars          6
1          MFGQ.SFA1CA    3209.200        NaN      F  Dollars          6
2          MFGQ.SFA1CA    2780.170        NaN      F  Dollars          6
3          MFGQ.SFA1CA    1933.010        NaN      F  Dollars          6
4          MFGQ.SFA1CA    2692.920        NaN      F  Dollars          6
...                ...         ...        ...    ...      ...        ...
30766      MFGQ.SFZ5KA   10643.807        NaN      F  Dollars          6
30767      MFGQ.SFZ5KA   10863.217        NaN      F  Dollars          6
30768      MFGQ.SFZ5KA    9086.747        NaN      F  Dollars          6
30769      MFGQ.SFZ5KA    9448.195        NaN      R  Dollars          6
30770      MFGQ.SFZ5KA   10449.981        NaN      F  Dollars          6

                                     Subject  \
0      Manufacturing Survey (ANZSIC06) - MFG
1      Manufacturing Survey (ANZSIC06) - MFG
2      Manufacturing Survey (ANZSIC06) - MFG
3      Manufacturing Survey (ANZSIC06) - MFG
4      Manufacturing Survey (ANZSIC06) - MFG
...                                      ...
30766  Manufacturing Survey (ANZSIC06) - MFG
30767  Manufacturing Survey (ANZSIC06) - MFG
30768  Manufacturing Survey (ANZSIC06) - MFG
30769  Manufacturing Survey (ANZSIC06) - MFG
30770  Manufacturing Survey (ANZSIC06) - MFG

                                                   Group  \
0      Industry by variable - Subannual Financial Col...
1      Industry by variable - Subannual Financial Col...
2      Industry by variable - Subannual Financial Col...
3      Industry by variable - Subannual Financial Col...
4      Industry by variable - Subannual Financial Col...
...                                                  ...
30766  Industry by variable - Subannual Financial Col...
30767  Industry by variable - Subannual Financial Col...
30768  Industry by variable - Subannual Financial Col...
30769  Industry by variable - Subannual Financial Col...
30770  Industry by variable - Subannual Financial Col...

                             Series_title_1  \
0      Meat and dairy product manufacturing
1      Meat and dairy product manufacturing
2      Meat and dairy product manufacturing
3      Meat and dairy product manufacturing
4      Meat and dairy product manufacturing
...                                     ...
30766                     All manufacturing
30767                     All manufacturing
30768                     All manufacturing
30769                     All manufacturing
30770                     All manufacturing

                                          Series_title_2  \
0                               Sales (operating income)
1                               Sales (operating income)
2                               Sales (operating income)
3                               Sales (operating income)
4                               Sales (operating income)
...                                                  ...
30766  Stocks of finished goods, trading goods and wo...
30767  Stocks of finished goods, trading goods and wo...
30768  Stocks of finished goods, trading goods and wo...
30769  Stocks of finished goods, trading goods and wo...
30770  Stocks of finished goods, trading goods and wo...

                                   Series_title_3 Series_title_4  \
0                                  Current prices     Unadjusted
1                                  Current prices     Unadjusted
2                                  Current prices     Unadjusted
3                                  Current prices     Unadjusted
4                                  Current prices     Unadjusted
...                                           ...            ...
30766  Deflated, at September 2010 quarter prices     Unadjusted
30767  Deflated, at September 2010 quarter prices     Unadjusted
30768  Deflated, at September 2010 quarter prices     Unadjusted
30769  Deflated, at September 2010 quarter prices     Unadjusted
30770  Deflated, at September 2010 quarter prices     Unadjusted

      Series_title_5
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
30766            NaN
30767            NaN
30768            NaN
30769            NaN
30770            NaN

[30771 rows x 13 columns]>

In [ ]:
print(df.merge)

<bound method DataFrame.merge of       Series_reference  Data_value Suppressed STATUS    UNITS  Magnitude  \
0          MFGQ.SFA1CA    2493.370        NaN      F  Dollars          6
1          MFGQ.SFA1CA    3209.200        NaN      F  Dollars          6
2          MFGQ.SFA1CA    2780.170        NaN      F  Dollars          6
3          MFGQ.SFA1CA    1933.010        NaN      F  Dollars          6
4          MFGQ.SFA1CA    2692.920        NaN      F  Dollars          6
...                ...         ...        ...    ...      ...        ...
30766      MFGQ.SFZ5KA   10643.807        NaN      F  Dollars          6
30767      MFGQ.SFZ5KA   10863.217        NaN      F  Dollars          6
30768      MFGQ.SFZ5KA    9086.747        NaN      F  Dollars          6
30769      MFGQ.SFZ5KA    9448.195        NaN      R  Dollars          6
30770      MFGQ.SFZ5KA   10449.981        NaN      F  Dollars          6

                                     Subject  \
0      Manufacturing Survey (ANZSIC06) - MFG
1      Manufacturing Survey (ANZSIC06) - MFG
2      Manufacturing Survey (ANZSIC06) - MFG
3      Manufacturing Survey (ANZSIC06) - MFG
4      Manufacturing Survey (ANZSIC06) - MFG
...                                      ...
30766  Manufacturing Survey (ANZSIC06) - MFG
30767  Manufacturing Survey (ANZSIC06) - MFG
30768  Manufacturing Survey (ANZSIC06) - MFG
30769  Manufacturing Survey (ANZSIC06) - MFG
30770  Manufacturing Survey (ANZSIC06) - MFG

                                                   Group  \
0      Industry by variable - Subannual Financial Col...
1      Industry by variable - Subannual Financial Col...
2      Industry by variable - Subannual Financial Col...
3      Industry by variable - Subannual Financial Col...
4      Industry by variable - Subannual Financial Col...
...                                                  ...
30766  Industry by variable - Subannual Financial Col...
30767  Industry by variable - Subannual Financial Col...
30768  Industry by variable - Subannual Financial Col...
30769  Industry by variable - Subannual Financial Col...
30770  Industry by variable - Subannual Financial Col...

                             Series_title_1  \
0      Meat and dairy product manufacturing
1      Meat and dairy product manufacturing
2      Meat and dairy product manufacturing
3      Meat and dairy product manufacturing
4      Meat and dairy product manufacturing
...                                     ...
30766                     All manufacturing
30767                     All manufacturing
30768                     All manufacturing
30769                     All manufacturing
30770                     All manufacturing

                                          Series_title_2  \
0                               Sales (operating income)
1                               Sales (operating income)
2                               Sales (operating income)
3                               Sales (operating income)
4                               Sales (operating income)
...                                                  ...
30766  Stocks of finished goods, trading goods and wo...
30767  Stocks of finished goods, trading goods and wo...
30768  Stocks of finished goods, trading goods and wo...
30769  Stocks of finished goods, trading goods and wo...
30770  Stocks of finished goods, trading goods and wo...

                                   Series_title_3 Series_title_4  \
0                                  Current prices     Unadjusted
1                                  Current prices     Unadjusted
2                                  Current prices     Unadjusted
3                                  Current prices     Unadjusted
4                                  Current prices     Unadjusted
...                                           ...            ...
30766  Deflated, at September 2010 quarter prices     Unadjusted
30767  Deflated, at September 2010 quarter prices     Unadjusted
30768  Deflated, at September 2010 quarter prices     Unadjusted
30769  Deflated, at September 2010 quarter prices     Unadjusted
30770  Deflated, at September 2010 quarter prices     Unadjusted

      Series_title_5
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
30766            NaN
30767            NaN
30768            NaN
30769            NaN
30770            NaN

[30771 rows x 13 columns]>

In [ ]:
print(df.sort_values)

<bound method DataFrame.sort_values of       Series_reference  Data_value Suppressed STATUS    UNITS  Magnitude  \
0          MFGQ.SFA1CA    2493.370        NaN      F  Dollars          6
1          MFGQ.SFA1CA    3209.200        NaN      F  Dollars          6
2          MFGQ.SFA1CA    2780.170        NaN      F  Dollars          6
3          MFGQ.SFA1CA    1933.010        NaN      F  Dollars          6
4          MFGQ.SFA1CA    2692.920        NaN      F  Dollars          6
...                ...         ...        ...    ...      ...        ...
30766      MFGQ.SFZ5KA   10643.807        NaN      F  Dollars          6
30767      MFGQ.SFZ5KA   10863.217        NaN      F  Dollars          6
30768      MFGQ.SFZ5KA    9086.747        NaN      F  Dollars          6
30769      MFGQ.SFZ5KA    9448.195        NaN      R  Dollars          6
30770      MFGQ.SFZ5KA   10449.981        NaN      F  Dollars          6

                                     Subject  \
0      Manufacturing Survey (ANZSIC06) - MFG
1      Manufacturing Survey (ANZSIC06) - MFG
2      Manufacturing Survey (ANZSIC06) - MFG
3      Manufacturing Survey (ANZSIC06) - MFG
4      Manufacturing Survey (ANZSIC06) - MFG
...                                      ...
30766  Manufacturing Survey (ANZSIC06) - MFG
30767  Manufacturing Survey (ANZSIC06) - MFG
30768  Manufacturing Survey (ANZSIC06) - MFG
30769  Manufacturing Survey (ANZSIC06) - MFG
30770  Manufacturing Survey (ANZSIC06) - MFG

                                                   Group  \
0      Industry by variable - Subannual Financial Col...
1      Industry by variable - Subannual Financial Col...
2      Industry by variable - Subannual Financial Col...
3      Industry by variable - Subannual Financial Col...
4      Industry by variable - Subannual Financial Col...
...                                                  ...
30766  Industry by variable - Subannual Financial Col...
30767  Industry by variable - Subannual Financial Col...
30768  Industry by variable - Subannual Financial Col...
30769  Industry by variable - Subannual Financial Col...
30770  Industry by variable - Subannual Financial Col...

                             Series_title_1  \
0      Meat and dairy product manufacturing
1      Meat and dairy product manufacturing
2      Meat and dairy product manufacturing
3      Meat and dairy product manufacturing
4      Meat and dairy product manufacturing
...                                     ...
30766                     All manufacturing
30767                     All manufacturing
30768                     All manufacturing
30769                     All manufacturing
30770                     All manufacturing

                                          Series_title_2  \
0                               Sales (operating income)
1                               Sales (operating income)
2                               Sales (operating income)
3                               Sales (operating income)
4                               Sales (operating income)
...                                                  ...
30766  Stocks of finished goods, trading goods and wo...
30767  Stocks of finished goods, trading goods and wo...
30768  Stocks of finished goods, trading goods and wo...
30769  Stocks of finished goods, trading goods and wo...
30770  Stocks of finished goods, trading goods and wo...

                                   Series_title_3 Series_title_4  \
0                                  Current prices     Unadjusted
1                                  Current prices     Unadjusted
2                                  Current prices     Unadjusted
3                                  Current prices     Unadjusted
4                                  Current prices     Unadjusted
...                                           ...            ...
30766  Deflated, at September 2010 quarter prices     Unadjusted
30767  Deflated, at September 2010 quarter prices     Unadjusted
30768  Deflated, at September 2010 quarter prices     Unadjusted
30769  Deflated, at September 2010 quarter prices     Unadjusted
30770  Deflated, at September 2010 quarter prices     Unadjusted

      Series_title_5
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
30766            NaN
30767            NaN
30768            NaN
30769            NaN
30770            NaN

[30771 rows x 13 columns]>

In [ ]:
print(dir(df))

['Data_value', 'Group', 'Magnitude', 'STATUS', 'Series_reference', 'Series_title_1', 'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5', 'Subject', 'Suppressed', 'T', 'UNITS', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [ ]:
print(df.isnull().sum())

Series_reference        0
Data_value            749
Suppressed          30769
STATUS                  0
UNITS                   0
Magnitude               0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2          0
Series_title_3          0
Series_title_4          0
Series_title_5      29277
dtype: int64

In [ ]:
df=df.dropna()
print(df.isnull().sum())

Series_reference    0
Data_value          0
Suppressed          0
STATUS              0
UNITS               0
Magnitude           0
Subject             0
Group               0
Series_title_1      0
Series_title_2      0
Series_title_3      0
Series_title_4      0
Series_title_5      0
dtype: int64